name: custom_camera_app
description: A production-ready Flutter camera app with Veepai SDK integration and AI features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  get_it: ^7.6.0
  
  # Reactive Programming
  rxdart: ^0.27.0
  
  # Network & Connectivity
  dio: ^5.3.0
  connectivity_plus: ^5.0.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  
  # Camera & Video
  camera: ^0.10.5
  video_player: ^2.7.0
  
  # AI/ML
  tflite_flutter: ^0.10.0
  image: ^4.0.0
  
  # Code Generation & Utilities
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  logger: ^2.0.0
  intl: ^0.18.0
  
  # UI & Styling
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.0
  
  # Veepai SDK (local dependency)
  vsdk:
    path: ../flutter-sdk-demo

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Testing
  mockito: ^5.4.0
  faker: ^2.1.0
  
  # Code Generation
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/ai_models/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

